/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 
 *
 * The version of the OpenAPI document: v3.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOverrideruleAdvancedRequestRequest {
    #[serde(rename = "mediaType")]
    pub media_type: String,
    #[serde(rename = "tmdbId")]
    pub tmdb_id: f64,
    #[serde(rename = "is4k", skip_serializing_if = "Option::is_none")]
    pub is4k: Option<bool>,
    #[serde(rename = "requestId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<Option<f64>>,
    #[serde(rename = "requestUser", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub request_user: Option<Option<f64>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<f64>>>,
    #[serde(rename = "serviceId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_id: Option<Option<f64>>,
}

impl CreateOverrideruleAdvancedRequestRequest {
    pub fn new(media_type: String, tmdb_id: f64) -> CreateOverrideruleAdvancedRequestRequest {
        CreateOverrideruleAdvancedRequestRequest {
            media_type,
            tmdb_id,
            is4k: None,
            request_id: None,
            request_user: None,
            tags: None,
            service_id: None,
        }
    }
}

