/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 
 *
 * The version of the OpenAPI document: v3.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOverrideruleAdvancedRequest2XxResponse {
    #[serde(rename = "rootFolder", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub root_folder: Option<Option<String>>,
    #[serde(rename = "profileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub profile_id: Option<Option<f64>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<f64>>>,
}

impl CreateOverrideruleAdvancedRequest2XxResponse {
    pub fn new() -> CreateOverrideruleAdvancedRequest2XxResponse {
        CreateOverrideruleAdvancedRequest2XxResponse {
            root_folder: None,
            profile_id: None,
            tags: None,
        }
    }
}

