/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 
 *
 * The version of the OpenAPI document: v3.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCache2XxResponseImageCacheTmdb {
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<f64>,
    #[serde(rename = "imageCount", skip_serializing_if = "Option::is_none")]
    pub image_count: Option<f64>,
}

impl GetCache2XxResponseImageCacheTmdb {
    pub fn new() -> GetCache2XxResponseImageCacheTmdb {
        GetCache2XxResponseImageCacheTmdb {
            size: None,
            image_count: None,
        }
    }
}

