/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 
 *
 * The version of the OpenAPI document: v3.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStatusAppdata2XxResponse {
    #[serde(rename = "appData", skip_serializing_if = "Option::is_none")]
    pub app_data: Option<bool>,
    #[serde(rename = "appDataPath", skip_serializing_if = "Option::is_none")]
    pub app_data_path: Option<String>,
    #[serde(rename = "appDataPermissions", skip_serializing_if = "Option::is_none")]
    pub app_data_permissions: Option<bool>,
}

impl GetStatusAppdata2XxResponse {
    pub fn new() -> GetStatusAppdata2XxResponse {
        GetStatusAppdata2XxResponse {
            app_data: None,
            app_data_path: None,
            app_data_permissions: None,
        }
    }
}

