/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 
 *
 * The version of the OpenAPI document: v3.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDiscoverMoviesLanguageByLanguage2XxResponse {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<f64>,
    #[serde(rename = "totalPages", skip_serializing_if = "Option::is_none")]
    pub total_pages: Option<f64>,
    #[serde(rename = "totalResults", skip_serializing_if = "Option::is_none")]
    pub total_results: Option<f64>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<Box<models::SpokenLanguage>>,
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::MovieResult>>,
}

impl GetDiscoverMoviesLanguageByLanguage2XxResponse {
    pub fn new() -> GetDiscoverMoviesLanguageByLanguage2XxResponse {
        GetDiscoverMoviesLanguageByLanguage2XxResponse {
            page: None,
            total_pages: None,
            total_results: None,
            language: None,
            results: None,
        }
    }
}

