/*
 * Seerr API
 *
 * This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 
 *
 * The version of the OpenAPI document: v3.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCache2XxResponseDnsCache {
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<Box<models::GetCache2XxResponseDnsCacheStats>>,
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<std::collections::HashMap<String, models::GetCache2XxResponseDnsCacheEntriesValue>>,
}

impl GetCache2XxResponseDnsCache {
    pub fn new() -> GetCache2XxResponseDnsCache {
        GetCache2XxResponseDnsCache {
            stats: None,
            entries: None,
        }
    }
}

